services:
    minio:
        image: quay.io/minio/minio
        container_name: minio
        ports:
            - 9000:9000
            - 9001:9001
        volumes:
            - ./data/minio:/data
        environment:
            - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
            - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadminpassword}
        command: server /data --console-address ":9001"
