services:
    minio:
        image: quay.io/minio/minio
        container_name: minio
        ports:
            - 9000:9000
            - 9001:9001
        volumes:
            - ./data/minio:/data
        environment:
            - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
            - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadminpassword}
        command: server /data --console-address ":9001"
    tcpdump:
        image: nicolaka/netshoot
        depends_on:
            - minio
        command: tcpdump -A -i eth0 port 9000 -w /data/minio.pcap
        network_mode: service:minio
        volumes:
            - $PWD/data/netshoot:/data
